<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jwparking"
 *
 * Auto generated by Extension Builder 2014-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Parking',
    'description' => 'Parking',
    'category' => 'plugin',
    'author' => ', Stefan Froemken',
    'author_email' => ', projects@jweiland.net',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.13-8.99.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
