<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jwparking"
 *
 * Auto generated by Extension Builder 2014-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Parking',
	'description' => 'Parking',
	'category' => 'plugin',
	'author' => ', Stefan Froemken',
	'author_email' => ', projects@jweiland.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);